/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    ForSize: typeof import('./src/views/4-size/ForSize.vue')['default']
    FourSize: typeof import('./src/components/FourSize.vue')['default']
    FourSizeIndex: typeof import('./src/views/4-size/FourSizeIndex.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    Picture: typeof import('./src/components/Picture.vue')['default']
    Playground: typeof import('./src/views/playground/Playground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/views/scroll/index.vue')['default']
  }
}
